keywordList1 = [
    "#fix ", "//fix ", " fix "," fix", "xxx ", " xxx", " ill","barf", " todo ", 
    "#todo","# todo" ,"//todo" ,"// todo" ,"/* todo", "/*todo", "hack", "fixm", "nuke", "ugli", "yuck",
    "crap", "ugly", "silly", "fixme", "hacky", "stupid", "kludge", "kaboom",
    "broken", "give up", "toss it", "retarded", "bail out", "ineffici", "at a loss",
    "implement", "take care", "this is bs", "workaround", "prolly a bug",
    "causes issue", "inconsistency", "this is wrong", "fix this crap",
    "probably a bug", "don’t use this", "this is uncool", "is problematic",
    "cause for issue", "get rid of this", "trial and error", "just abandon it",
    "certainly buggy", "abandon all hope", "some fatal error", "temporary crutch",
    "remove this code", "may cause problem", "temporary solution",
    "this can be a mess", "workaround for bug", "there is a problem",
    "give up and go away", "it doesn’t work yet", "this isn’t very solid",
    "you can be unhappy now", "something’s gone wrong", "something bad happened",
    "is this next line safe", "this isn’t quite right", "risk of this blowing up",
    "this doesn’t look right", "hang our heads in shame",
    "is this line really safe", "hope everything will work",
    "something bad is going on", "treat this as a soft error",
    "doubt that this would work", "something serious is wrong",
    "remove me before production", "this is temporary and will go away",
    "unknown why we ever experience this", "this indicates a more fundamental problem"
]


keywordList2 = [
    "#fix ",
    "//fix ",
    " fix "
    " fix",
    "hack",
    "nuke",
    "yuck",
    "hacky",
    "fixme",
    "kludge",
    "give up",
    "retarded",
    "at a loss",
    "this is bs",
    "prolly a bug",
    "fix this crap",
    "is problematic",
    "probably a bug",
    "trial and error",
    "get rid of this",
    "certainly buggy",
    "temporary crutch",
    "abandon all hope",
    "workaround for bug",
    "this can be a mess",
    "give up and go away",
    "this isn’t very solid",
    "this isn’t quite right",
    "something bad happened",
    "hang our heads in shame",
    "risk of this blowing up",
    "something bad is going on",
    "treat this as a soft error",
    "doubt that this would work",
    "this is temporary and will go away",
    "this indicates a more fundamental problem",
    "ugly",
    "barf",
    "crap",
    "silly",
    "stupid",
    "kaboom",
    "toss it",
    "bail out",
    "take care",
    "causes issue",
    "this is wrong",
    "inconsistency",
    "don’t use this",
    "this is uncool",
    "cause for issue",
    "just abandon it",
    "remove this code",
    "some fatal error",
    "may cause problem",
    "temporary solution",
    "there is a problem",
    "it doesn’t work yet",
    "something’s gone wrong",
    "is this next line safe",
    "you can be unhappy now",
    "this doesn’t look right",
    "is this line really safe",
    "hope everything will work",
    "something serious is wrong",
    "remove me before production",
    "unknown why we ever experience this"
]